name: Infrastructure and App Deploy

on:
  push:
    paths:
      - '**.tf'
      - 'docker-compose.yml'

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Instance IP
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: |
          echo "SERVER_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Wait for SSH connection
        run: |
          echo "Waiting for SSH to wake up..."
          for i in {1..10}; do
            nc -zv ${{ env.SERVER_IP }} 22 && break || sleep 5
          done

      - name: Copy docker-compose.yml via SCP
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Debug cloud-init
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== cloud-init status ==="
            sudo cloud-init status --long || true

            echo "=== cloud-init output log ==="
            sudo tail -n 300 /var/log/cloud-init-output.log || true

            echo "=== cloud-init main log ==="
            sudo tail -n 300 /var/log/cloud-init.log || true

            echo "=== os-release ==="
            cat /etc/os-release || true

            echo "=== docker path ==="
            which docker || true
            sudo which docker || true

      - name: Pull and Run Containers
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            echo "Waiting for cloud-init to finish installation..."
            sudo cloud-init status --wait
            
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            sudo docker compose up -d --force-recreate