name: Infrastructure and App Deploy

on:
  push:
    paths:
      - '**.tf'

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Instance IP
        if: github.ref == 'refs/heads/main'
        run: |
          echo "SERVER_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy docker-compose.yml via SCP
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/"

      - name: Pull and Run Containers
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            until sudo docker info > /dev/null 2>&1; do echo "Waiting for docker..."; sleep 5; done
            
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            sudo docker pull yurii2288/lab4_app:latest
            sudo docker pull yurii2288/nginx:latest
            sudo docker pull containrrr/watchtower:latest
            
            sudo docker compose up -d --force-recreate